version: '2'

services:
   jenkins:
    image: huguescarange/lesgoys-vaolo-dockerjenkins
    container_name: lesgoys_jenkins
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/tmp/jenkins/jenkins_home:/var/jenkins_home
   staging:
    image: huguescarange/lesgoys-vaolo-dockerstaging
    container_name: lesgoys_staging
    restart: always
    ports:
      - 8100:8100
   prod:
    image: huguescarange/lesgoys-vaolo-dockerprod
    container_name: lesgoys_prod
    restart: always
    ports:
      - 8101:8101
   test:
    image: huguescarange/lesgoys-vaolo-dockertest
    container_name: lesgoys_test
    ports:
      - 8086:8086

