version: '2'

services:
  jenkins:
    image: huguescarange/lesgoys-vaolo-dockerjenkins
    container_name: lesgoys_jenkins
    restart: always
    ports:
      - 8080:5080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/tmp/jenkins/jenkins_home:/var/jenkins_home
   ionic:
    image: huguescarange/lesgoys-vaolo-dockerstaging
    container_name: lesgoys_staging
    restart: always
    ports:
      - 8100:5100
   karma:
    image: huguescarange/lesgoys-vaolo-dockertest
    container_name: lesgoys_test
    ports:
      - 8086:5086
